n = input('Digite algo:')
print('O tipo primitivo de {} é'.format(n), type(n))
print('Ele é numerico? ',n.isnumeric())
print('Ele é alfabético ',n.isalpha())
print('Ele tem espaços? ',n.isspace())
print('Ele é alfanumérico? ',n.isalnum())
print('Está em maiúsculas? ',n.isupper())
print('Está em minúsculas? ',n.islower())
print('está capitalizada? ',n.istitle())
